#!/usr/bin/env bash
# configure the load balancer, install haproxy
sudo apt update
sudo apt -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 16742-web-01 34.204.166.252:80 check\n\tserver 16742-web-02 18.205.192.79:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
