#!/usr/bin/env bash
# configure the load balancer, install haproxy

# Update package lists
sudo apt update

# Install HAProxy
sudo apt -y install haproxy

# Enable HAProxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy

# Configure HAProxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 502158-web-01 100.26.120.217:80 check\n\tserver 502158-web-02 100.26.57.162:80 check\n' /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart
