#!/usr/bin/env bash
# This displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while IFS=: read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
