#!/usr/bin/env bash
# Using a while loop to display "Best School" 10 times


# Counter variable
counter=0

# Using an until loop to display "Best School" 10 times
until [ $counter -eq 10 ]; do
    echo "Best School"
    ((counter++))
done
