#!/usr/bin/env bash
# Using a while loop to display "Best School" 10 times


# Counter variable
num=0

# Using a while loop to display "Best School" 10 times
while [ $num -lt 10 ]
do
    if [ $num -eq 8 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((num++))
done
