#!/usr/bin/env bash
# This script prints "bad luck" 4th iteration, "good luck" on the 8th iteration, and "Holberton School" for other iterations
count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "4"
            echo "Bad luck from China"
            ;;
        9)
            echo "9"
            echo "Bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "Bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    ((count++))
done
