#!/bin/bash

# Make all files in the current directory executable
chmod +x *

# Make README.md non-executable
chmod -x README.md

 git config --global user.email "endywezy@gmail.com"
 git config --global user.name "endywezy"

# Add all files to git, commit changes, and push to the remote repository
git add . && git commit -m 'ALX ' && git push

