#!/bin/bash

# Make all files in the current directory executable
chmod +x *

# Make README.md non-executable
chmod -x README.md

# Add all files to git, commit changes, and push to the remote repository
git add . && git commit -m 'SSH Server' && git push

